export const itemslist = [
  {
    id: 1,
    title: "Paneer Tikka",
    type: "dairy",
    description: "Freshly made Paneer with masala Zaika",
    filename: "0.jpg",
    height: 600,
    width: 400,
    price: 28.1,
    rating: 4,
    img: require("./dishes/paneertikka.jpg"),
    price: 200,
  },
  {
    id: 2,
    title: "Paneer Chilli",
    type: "fruit",
    description: "Half-cooked Paneer served with chilli sauce ",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/chillipaneer.webp"),
    price: 250,
  },
  {
    id: 3,
    title: "Garlic Paneer",
    type: "vegetable",
    description: "Half-cooked Paneer served with garlic cheese and vegetables",
    filename: "2.jpg",
    height: 450,
    width: 299,
    price: 18.95,
    rating: 3,
    img: require("./dishes/garlicpaneer.jpg"),
    price: 230,
  },
  {
    id: 4,
    title: "Paneer Popcorn",
    type: "dairy",
    description: "Crunchy paneer bites with red sauce",
    filename: "3.jpg",
    height: 600,
    width: 399,
    price: 17.68,
    rating: 4,
    img: require("./dishes/paneerpopcorn.webp"),
    price: 240,
  },
  {
    id: 5,
    title: "Dal Makhani",
    type: "dairy",
    description: "Freshy cheesy Dal with masala Zaika ",
    filename: "0.jpg",
    height: 600,
    width: 400,
    price: 28.1,
    rating: 4,
    img: require("./dishes/dalmakhani.jpg"),
    price: 250,
  },
  {
    id: 6,
    title: "Mix Veg",
    type: "fruit",
    description: "Sweet fresh mixed vegetables with awesome taste",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/mixveg.webp"),
    price: 260,
  },
  {
    id: 7,
    title: "Chaap",
    type: "fruit",
    description: "Freshly made chaap with indian masala",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/chaap.webp"),
    price: 270,
  },
  {
    id: 8,
    title: "Paneer Lababdaar",
    type: "fruit",
    description: "Sweet fresh Paneer with onion, capsicum and tomato gravy",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/paneerlababdaar.webp"),
    price: 280,
  },
  {
    id: 9,
    title: "Malai Kofta",
    type: "fruit",
    description: "Freshly made Malai Kofta with cheesy style ",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/malaikofta.jpg"),
    price: 290,
  },
  {
    id: 10,
    title: "Rajma Masala",
    type: "fruit",
    description:
      "Dish made with kidney beans, onions, tomatoes, spices and herbs",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/rajmamasala.jpg"),
    price: 300,
  },
  {
    id: 11,
    title: "Chhole Masala",
    type: "fruit",
    description: "Dish made with chickpeas, onions, tomatoes, spices and herbs",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/chholemasala.jpg"),
    price: 310,
  },
  {
    id: 12,
    title: "Paneer Butter Masala",
    type: "fruit",
    description:
      "Creamy curry made with paneer, spices, onions, tomatoes, cashews and butter.",
    filename: "1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    img: require("./dishes/paneerbuttermasala.webp"),
    price: 320,
  },
];
